services:
  deep_knowledge_agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deep_knowledge_agent
    ports:
      - "3773:3773"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}


    env_file:
      - .env
    volumes:
      - ./deep_knowledge_agent:/app/deep_knowledge_agent
      - ./agent_config.json:/app/agent_config.json
    restart: unless-stopped
    networks:
      - deep_knowledge_agent-network


networks:
  deep_knowledge_agent-network:
    driver: bridge
